package com.example.vitalwearclonev1.gridbattle

/**
 * Battle-chip library for Grid Battle mode (2026-09-25).
 *
 * ~150 chips with original names across 10 families: Blasters, Blades,
 * Launchers, Beams, Storms, Summons, Traps, Supports, Cannons, Seekers.
 * Tiers: 115 STANDARD / 25 MEGA / 10 GIGA.
 *
 * Letter codes enable folder code-matching (same code or '*' wildcard).
 * Damage is per hit; multiply by [hits] for multi-hit totals.
 * Exact balance numbers are tuned in the playtest pass - treat these
 * as the starting feel, not the final word.
 */
enum class ChipTier { STANDARD, MEGA, GIGA }

enum class ChipElement { FIRE, WATER, ELEC, WOOD, SWORD, WIND, CURSOR, BREAK, PLUS, NULL }

enum class EffectKind { PROJECTILE, MELEE, LOB, BEAM, SUMMON, TRAP, SUPPORT, SWORD }

data class BattleChip(
    val id: Int,
    val name: String,
    val tier: ChipTier,
    val element: ChipElement,
    val damage: Int,
    val codes: List<Char>,
    val mb: Int,
    val hits: Int = 1,
    val effectKind: EffectKind,
    val description: String
)

object ChipLibrary {
    val chips: List<BattleChip> = listOf(
        BattleChip(1, "PalmBlaster", ChipTier.STANDARD, ChipElement.NULL, 20, listOf('A'), 8, 1, EffectKind.PROJECTILE, "Fires a quick burst of palm energy straight ahead."),
        BattleChip(2, "EmberShot", ChipTier.STANDARD, ChipElement.FIRE, 30, listOf('A', 'B'), 12, 1, EffectKind.PROJECTILE, "Hurls a sizzling ember that scorches the panel ahead."),
        BattleChip(3, "AquaPellet", ChipTier.STANDARD, ChipElement.WATER, 30, listOf('B'), 12, 1, EffectKind.PROJECTILE, "Spits a high-pressure water pellet down the row."),
        BattleChip(4, "VoltPip", ChipTier.STANDARD, ChipElement.ELEC, 30, listOf('B', 'C'), 12, 1, EffectKind.PROJECTILE, "Zaps a crackling spark across the row."),
        BattleChip(5, "LeafDart", ChipTier.STANDARD, ChipElement.WOOD, 30, listOf('C'), 12, 1, EffectKind.PROJECTILE, "Flings a razor-sharp leaf dart forward."),
        BattleChip(6, "TwinPalm", ChipTier.STANDARD, ChipElement.NULL, 15, listOf('A', 'C'), 14, 2, EffectKind.PROJECTILE, "Two quick palm bursts in rapid succession."),
        BattleChip(7, "SearBlast", ChipTier.STANDARD, ChipElement.FIRE, 40, listOf('A'), 16, 1, EffectKind.PROJECTILE, "A roaring fireball that leaves embers behind."),
        BattleChip(8, "TideLance", ChipTier.STANDARD, ChipElement.WATER, 40, listOf('B'), 16, 1, EffectKind.PROJECTILE, "A piercing lance of rushing water."),
        BattleChip(9, "SparkArc", ChipTier.STANDARD, ChipElement.ELEC, 40, listOf('C'), 16, 1, EffectKind.PROJECTILE, "Lightning that arcs across a single panel."),
        BattleChip(10, "ThornVolley", ChipTier.STANDARD, ChipElement.WOOD, 20, listOf('B', 'C'), 18, 2, EffectKind.PROJECTILE, "A pair of spinning thorn seeds."),
        BattleChip(11, "GustPuff", ChipTier.STANDARD, ChipElement.WIND, 30, listOf('A', 'B'), 12, 1, EffectKind.PROJECTILE, "A sudden gust that shoves the foe back a panel."),
        BattleChip(12, "PebblePop", ChipTier.STANDARD, ChipElement.NULL, 10, listOf('A'), 14, 3, EffectKind.PROJECTILE, "Three bouncing pebbles. Fast, light, annoying."),
        BattleChip(13, "CinderSpray", ChipTier.STANDARD, ChipElement.FIRE, 15, listOf('B'), 18, 3, EffectKind.PROJECTILE, "A spray of tiny burning cinders."),
        BattleChip(14, "BubblePop", ChipTier.STANDARD, ChipElement.WATER, 50, listOf('C'), 20, 1, EffectKind.PROJECTILE, "A fat bubble that bursts on impact."),
        BattleChip(15, "StaticSnap", ChipTier.STANDARD, ChipElement.ELEC, 50, listOf('A', 'B'), 20, 1, EffectKind.PROJECTILE, "A loud snap of angry static electricity."),
        BattleChip(16, "BarkChip", ChipTier.STANDARD, ChipElement.WOOD, 50, listOf('B', 'C'), 20, 1, EffectKind.PROJECTILE, "A heavy chunk of enchanted bark."),
        BattleChip(17, "DustDevil", ChipTier.STANDARD, ChipElement.WIND, 40, listOf('A', 'C'), 22, 2, EffectKind.PROJECTILE, "A tiny twister that hits twice."),
        BattleChip(18, "IronPea", ChipTier.STANDARD, ChipElement.NULL, 60, listOf('A'), 24, 1, EffectKind.PROJECTILE, "One heavy iron pea. It really hurts."),
        BattleChip(19, "MagmaGlob", ChipTier.STANDARD, ChipElement.FIRE, 60, listOf('B'), 24, 1, EffectKind.PROJECTILE, "A molten glob that splats on contact."),
        BattleChip(20, "FrostShard", ChipTier.STANDARD, ChipElement.WATER, 60, listOf('C'), 24, 1, EffectKind.PROJECTILE, "A freezing shard that chills to the bone."),
        BattleChip(21, "TeslaTick", ChipTier.STANDARD, ChipElement.ELEC, 60, listOf('A', 'B'), 24, 1, EffectKind.PROJECTILE, "A building charge released all at once."),
        BattleChip(22, "BrambleBall", ChipTier.STANDARD, ChipElement.WOOD, 60, listOf('B', 'C'), 24, 1, EffectKind.PROJECTILE, "A rolling ball of sharp brambles."),
        BattleChip(23, "CycloneSeed", ChipTier.STANDARD, ChipElement.WIND, 70, listOf('A', 'C'), 28, 1, EffectKind.PROJECTILE, "A seed that blooms into a mini cyclone."),
        BattleChip(24, "StarBit", ChipTier.STANDARD, ChipElement.NULL, 70, listOf('A', 'B', 'C'), 28, 1, EffectKind.PROJECTILE, "A falling star-bit with real punch."),
        BattleChip(25, "TriBlaster", ChipTier.MEGA, ChipElement.NULL, 90, listOf('A', 'B'), 45, 3, EffectKind.PROJECTILE, "Three palm bursts fanning out at once."),
        BattleChip(26, "InfernoJet", ChipTier.MEGA, ChipElement.FIRE, 120, listOf('B', 'C'), 55, 1, EffectKind.PROJECTILE, "A jet of roaring flame down the whole row."),
        BattleChip(27, "TsunamiOrb", ChipTier.MEGA, ChipElement.WATER, 120, listOf('A', 'C'), 55, 1, EffectKind.PROJECTILE, "A crushing orb of deep-sea pressure."),
        BattleChip(28, "StormCell", ChipTier.MEGA, ChipElement.ELEC, 120, listOf('A', 'B', 'C'), 55, 1, EffectKind.PROJECTILE, "A whole storm cloud packed into one bolt."),
        BattleChip(29, "SunLance", ChipTier.GIGA, ChipElement.FIRE, 300, listOf('A', 'B'), 80, 1, EffectKind.PROJECTILE, "A lance of pure sunlight. Devastating."),
        BattleChip(30, "VoidRound", ChipTier.GIGA, ChipElement.NULL, 280, listOf('*'), 85, 1, EffectKind.PROJECTILE, "A shot that tears a tiny hole in the air itself."),
        BattleChip(31, "ArcBlade", ChipTier.STANDARD, ChipElement.SWORD, 40, listOf('S'), 14, 1, EffectKind.SWORD, "A quick horizontal sword slash."),
        BattleChip(32, "TwinFang", ChipTier.STANDARD, ChipElement.SWORD, 30, listOf('S', 'K'), 16, 2, EffectKind.SWORD, "Two fast fang slashes, one after the other."),
        BattleChip(33, "WideArc", ChipTier.STANDARD, ChipElement.SWORD, 50, listOf('K'), 18, 1, EffectKind.SWORD, "A wide slash that nicks the panels beside you too."),
        BattleChip(34, "QuickDraw", ChipTier.STANDARD, ChipElement.SWORD, 30, listOf('K', 'L'), 12, 1, EffectKind.SWORD, "A blink-fast draw slash. Very hard to dodge."),
        BattleChip(35, "HeavyChop", ChipTier.STANDARD, ChipElement.SWORD, 70, listOf('L'), 24, 1, EffectKind.SWORD, "A slow, heavy overhead chop."),
        BattleChip(36, "SpinCut", ChipTier.STANDARD, ChipElement.SWORD, 25, listOf('S', 'L'), 18, 2, EffectKind.SWORD, "A spinning double slash."),
        BattleChip(37, "MoonSlice", ChipTier.STANDARD, ChipElement.SWORD, 60, listOf('S'), 22, 1, EffectKind.SWORD, "A graceful crescent-moon cut."),
        BattleChip(38, "FangRush", ChipTier.STANDARD, ChipElement.SWORD, 40, listOf('K'), 24, 2, EffectKind.SWORD, "A dash-slash, then a slash on the way back."),
        BattleChip(39, "CrossCut", ChipTier.STANDARD, ChipElement.SWORD, 35, listOf('S', 'K'), 22, 2, EffectKind.SWORD, "An X-shaped double cut."),
        BattleChip(40, "SkyRend", ChipTier.STANDARD, ChipElement.SWORD, 70, listOf('L'), 26, 1, EffectKind.SWORD, "A leaping slash that comes down from above."),
        BattleChip(41, "FlameTongue", ChipTier.STANDARD, ChipElement.FIRE, 50, listOf('S', 'L'), 20, 1, EffectKind.SWORD, "A blade wreathed in living flame."),
        BattleChip(42, "TideFang", ChipTier.STANDARD, ChipElement.WATER, 50, listOf('K', 'L'), 20, 1, EffectKind.SWORD, "A sword forged from rushing water."),
        BattleChip(43, "StormBrand", ChipTier.STANDARD, ChipElement.ELEC, 50, listOf('S', 'K', 'L'), 20, 1, EffectKind.SWORD, "A lightning-forged brand that crackles."),
        BattleChip(44, "RootCleaver", ChipTier.STANDARD, ChipElement.WOOD, 50, listOf('S'), 20, 1, EffectKind.SWORD, "A cleaver grown from ironwood."),
        BattleChip(45, "DragonArc", ChipTier.MEGA, ChipElement.SWORD, 120, listOf('S', 'K'), 50, 1, EffectKind.SWORD, "A slash with a dragon's fury behind it."),
        BattleChip(46, "TriMoon", ChipTier.MEGA, ChipElement.SWORD, 100, listOf('K', 'L'), 55, 3, EffectKind.SWORD, "Three crescent slashes in a single breath."),
        BattleChip(47, "InfernoBrand", ChipTier.MEGA, ChipElement.FIRE, 140, listOf('S', 'K', 'L'), 60, 1, EffectKind.SWORD, "A greatsword of pure wildfire."),
        BattleChip(48, "WorldCleaver", ChipTier.GIGA, ChipElement.SWORD, 350, listOf('S'), 90, 1, EffectKind.SWORD, "One cut that splits the entire row."),
        BattleChip(49, "LobBall", ChipTier.STANDARD, ChipElement.NULL, 40, listOf('G'), 14, 1, EffectKind.LOB, "Lobs a boom-ball that lands two panels ahead."),
        BattleChip(50, "SeedBomb", ChipTier.STANDARD, ChipElement.WOOD, 40, listOf('G', 'M'), 14, 1, EffectKind.LOB, "A seed that bursts into thorns where it lands."),
        BattleChip(51, "SizzlePop", ChipTier.STANDARD, ChipElement.FIRE, 50, listOf('M'), 18, 1, EffectKind.LOB, "A firecracker lobbed over the front line."),
        BattleChip(52, "SplashDrop", ChipTier.STANDARD, ChipElement.WATER, 50, listOf('M', 'D'), 18, 1, EffectKind.LOB, "A water balloon dropped from above."),
        BattleChip(53, "PopRocket", ChipTier.STANDARD, ChipElement.NULL, 60, listOf('D'), 22, 1, EffectKind.LOB, "A tiny rocket that arcs up and booms down."),
        BattleChip(54, "AcornMortar", ChipTier.STANDARD, ChipElement.WOOD, 60, listOf('G', 'D'), 22, 1, EffectKind.LOB, "An iron acorn fired sky-high."),
        BattleChip(55, "CinderShell", ChipTier.STANDARD, ChipElement.FIRE, 70, listOf('G'), 26, 1, EffectKind.LOB, "A shell packed tight with burning cinders."),
        BattleChip(56, "GeyserPop", ChipTier.STANDARD, ChipElement.WATER, 70, listOf('M'), 26, 1, EffectKind.LOB, "Erupts in a geyser under the target panel."),
        BattleChip(57, "ClusterToss", ChipTier.STANDARD, ChipElement.NULL, 30, listOf('D'), 24, 3, EffectKind.LOB, "Three mini-bombs scattered where it lands."),
        BattleChip(58, "StickyGoo", ChipTier.STANDARD, ChipElement.WOOD, 30, listOf('G', 'M'), 16, 1, EffectKind.LOB, "Sticky sap that slows whatever it splats."),
        BattleChip(59, "ThunderDrop", ChipTier.STANDARD, ChipElement.ELEC, 60, listOf('M', 'D'), 22, 1, EffectKind.LOB, "Calls a lightning strike onto the target panel."),
        BattleChip(60, "BigBertha", ChipTier.MEGA, ChipElement.NULL, 120, listOf('G', 'M'), 50, 1, EffectKind.LOB, "A huge shell that shakes three panels."),
        BattleChip(61, "VolcanoLob", ChipTier.MEGA, ChipElement.FIRE, 140, listOf('M', 'D'), 58, 1, EffectKind.LOB, "A volcano in a can, lobbed far."),
        BattleChip(62, "MeteorCall", ChipTier.GIGA, ChipElement.NULL, 320, listOf('G'), 88, 1, EffectKind.LOB, "Drops a meteor on the enemy's side."),
        BattleChip(63, "ZapLine", ChipTier.STANDARD, ChipElement.ELEC, 40, listOf('Z'), 14, 1, EffectKind.BEAM, "A piercing line of lightning."),
        BattleChip(64, "HeatRay", ChipTier.STANDARD, ChipElement.FIRE, 50, listOf('Z', 'P'), 18, 1, EffectKind.BEAM, "A searing ray that burns through the row."),
        BattleChip(65, "FrostBeam", ChipTier.STANDARD, ChipElement.WATER, 50, listOf('P'), 18, 1, EffectKind.BEAM, "A freezing beam that pierces everything."),
        BattleChip(66, "DrillBeam", ChipTier.STANDARD, ChipElement.NULL, 60, listOf('P', 'R'), 22, 1, EffectKind.BEAM, "A spinning drill of pure force."),
        BattleChip(67, "GustSpear", ChipTier.STANDARD, ChipElement.WIND, 40, listOf('R'), 14, 1, EffectKind.BEAM, "A spear of solid, screaming wind."),
        BattleChip(68, "ThornRay", ChipTier.STANDARD, ChipElement.WOOD, 50, listOf('Z', 'R'), 18, 1, EffectKind.BEAM, "A piercing ray of hardened thorns."),
        BattleChip(69, "PulseWave", ChipTier.STANDARD, ChipElement.ELEC, 30, listOf('Z'), 18, 2, EffectKind.BEAM, "Two quick electric pulses down the row."),
        BattleChip(70, "SolarThread", ChipTier.STANDARD, ChipElement.FIRE, 60, listOf('P'), 22, 1, EffectKind.BEAM, "A thread of sunlight, thin and unstoppable."),
        BattleChip(71, "NeedleJet", ChipTier.STANDARD, ChipElement.NULL, 70, listOf('R'), 26, 1, EffectKind.BEAM, "A needle-thin jet at blinding speed."),
        BattleChip(72, "StormLance", ChipTier.MEGA, ChipElement.ELEC, 130, listOf('Z', 'P'), 52, 1, EffectKind.BEAM, "A lance of stormlight through every panel."),
        BattleChip(73, "MagmaDrill", ChipTier.MEGA, ChipElement.FIRE, 150, listOf('P', 'R'), 60, 1, EffectKind.BEAM, "A drill bit of living magma."),
        BattleChip(74, "StarSpear", ChipTier.GIGA, ChipElement.NULL, 380, listOf('Z'), 92, 1, EffectKind.BEAM, "A spear thrown from the stars themselves."),
        BattleChip(75, "EmberRain", ChipTier.STANDARD, ChipElement.FIRE, 20, listOf('T'), 20, 3, EffectKind.PROJECTILE, "Burning embers rain on the foe's area."),
        BattleChip(76, "HailFall", ChipTier.STANDARD, ChipElement.WATER, 20, listOf('T', 'W'), 20, 3, EffectKind.PROJECTILE, "Sharp hailstones pelt the enemy side."),
        BattleChip(77, "SparkShower", ChipTier.STANDARD, ChipElement.ELEC, 20, listOf('W'), 20, 3, EffectKind.PROJECTILE, "A shower of angry sparks."),
        BattleChip(78, "LeafStorm", ChipTier.STANDARD, ChipElement.WOOD, 20, listOf('W', 'H'), 20, 3, EffectKind.PROJECTILE, "A whirlwind of razor leaves."),
        BattleChip(79, "DustBlast", ChipTier.STANDARD, ChipElement.WIND, 25, listOf('H'), 18, 2, EffectKind.PROJECTILE, "A blasting wave of stinging dust."),
        BattleChip(80, "CinderSwarm", ChipTier.STANDARD, ChipElement.FIRE, 15, listOf('T', 'H'), 22, 4, EffectKind.PROJECTILE, "A swarm of biting fire-flies."),
        BattleChip(81, "BubbleBurst", ChipTier.STANDARD, ChipElement.WATER, 25, listOf('T'), 18, 2, EffectKind.PROJECTILE, "Bursting bubbles, double the splash."),
        BattleChip(82, "VoltFlurry", ChipTier.STANDARD, ChipElement.ELEC, 15, listOf('W'), 22, 4, EffectKind.PROJECTILE, "A flurry of tiny lightning strikes."),
        BattleChip(83, "PollenPuff", ChipTier.STANDARD, ChipElement.WOOD, 25, listOf('H'), 18, 2, EffectKind.PROJECTILE, "A puff of stinging pollen, twice."),
        BattleChip(84, "HowlWind", ChipTier.STANDARD, ChipElement.WIND, 35, listOf('T', 'W'), 24, 2, EffectKind.PROJECTILE, "A howling gale that strikes twice."),
        BattleChip(85, "Firestorm", ChipTier.MEGA, ChipElement.FIRE, 60, listOf('T', 'H'), 55, 3, EffectKind.PROJECTILE, "A true firestorm over the enemy side."),
        BattleChip(86, "Deluge", ChipTier.MEGA, ChipElement.WATER, 60, listOf('W', 'H'), 55, 3, EffectKind.PROJECTILE, "A crushing, endless downpour."),
        BattleChip(87, "Tempest", ChipTier.MEGA, ChipElement.WIND, 70, listOf('T', 'W', 'H'), 60, 3, EffectKind.PROJECTILE, "A raging tempest in three waves."),
        BattleChip(88, "Cataclysm", ChipTier.GIGA, ChipElement.NULL, 150, listOf('T'), 95, 3, EffectKind.PROJECTILE, "The sky itself falls. Three times."),
        BattleChip(89, "PupCall", ChipTier.STANDARD, ChipElement.NULL, 40, listOf('V'), 12, 1, EffectKind.SUMMON, "A data-pup lunges at the nearest foe."),
        BattleChip(90, "EmberImp", ChipTier.STANDARD, ChipElement.FIRE, 50, listOf('V', 'N'), 16, 1, EffectKind.SUMMON, "A fire imp that hurls one fireball."),
        BattleChip(91, "BubbleBuddy", ChipTier.STANDARD, ChipElement.WATER, 50, listOf('N'), 16, 1, EffectKind.SUMMON, "A bubble buddy that body-slams once."),
        BattleChip(92, "ZapBat", ChipTier.STANDARD, ChipElement.ELEC, 50, listOf('N', 'U'), 16, 1, EffectKind.SUMMON, "A zap bat that dive-bombs the foe."),
        BattleChip(93, "TwigSprite", ChipTier.STANDARD, ChipElement.WOOD, 50, listOf('U'), 16, 1, EffectKind.SUMMON, "A twig sprite that thorn-slaps once."),
        BattleChip(94, "GustWisp", ChipTier.STANDARD, ChipElement.WIND, 40, listOf('V', 'U'), 14, 1, EffectKind.SUMMON, "A wisp that rams with a gust."),
        BattleChip(95, "RockGolem", ChipTier.STANDARD, ChipElement.NULL, 70, listOf('V'), 24, 1, EffectKind.SUMMON, "A rock golem that throws one boulder."),
        BattleChip(96, "CinderFox", ChipTier.STANDARD, ChipElement.FIRE, 60, listOf('N'), 20, 1, EffectKind.SUMMON, "A cinder fox with a blazing pounce."),
        BattleChip(97, "FrostNewt", ChipTier.STANDARD, ChipElement.WATER, 60, listOf('U'), 20, 1, EffectKind.SUMMON, "A frost newt with an icy tackle."),
        BattleChip(98, "ThunderDrake", ChipTier.MEGA, ChipElement.ELEC, 120, listOf('V', 'N'), 52, 1, EffectKind.SUMMON, "A drake that calls down one huge bolt."),
        BattleChip(99, "MagmaTitan", ChipTier.MEGA, ChipElement.FIRE, 140, listOf('N', 'U'), 58, 1, EffectKind.SUMMON, "A titan that hurls a molten boulder."),
        BattleChip(100, "StarBeast", ChipTier.GIGA, ChipElement.NULL, 300, listOf('*'), 90, 1, EffectKind.SUMMON, "A beast of starlight. One earth-shaking charge."),
        BattleChip(101, "PopMine", ChipTier.STANDARD, ChipElement.NULL, 50, listOf('X'), 16, 1, EffectKind.TRAP, "A mine that pops when stepped on."),
        BattleChip(102, "EmberSnare", ChipTier.STANDARD, ChipElement.FIRE, 60, listOf('X', 'E'), 20, 1, EffectKind.TRAP, "A fire trap hiding on a panel."),
        BattleChip(103, "FrostSnare", ChipTier.STANDARD, ChipElement.WATER, 60, listOf('E'), 20, 1, EffectKind.TRAP, "An icy trap that bites deep cold."),
        BattleChip(104, "SparkSnare", ChipTier.STANDARD, ChipElement.ELEC, 60, listOf('E', 'Q'), 20, 1, EffectKind.TRAP, "A hidden coil of sparks."),
        BattleChip(105, "ThornSnare", ChipTier.STANDARD, ChipElement.WOOD, 60, listOf('Q'), 20, 1, EffectKind.TRAP, "Thorns that spring from the panel."),
        BattleChip(106, "GooPit", ChipTier.STANDARD, ChipElement.WOOD, 30, listOf('X', 'Q'), 12, 1, EffectKind.TRAP, "Sticky goo that slows and nips."),
        BattleChip(107, "FlashMine", ChipTier.STANDARD, ChipElement.ELEC, 70, listOf('X'), 24, 1, EffectKind.TRAP, "A blinding flash-mine."),
        BattleChip(108, "BoomShroom", ChipTier.STANDARD, ChipElement.WOOD, 70, listOf('E'), 24, 1, EffectKind.TRAP, "Looks like a mushroom. Is a bomb."),
        BattleChip(109, "TidePool", ChipTier.STANDARD, ChipElement.WATER, 40, listOf('Q'), 14, 1, EffectKind.TRAP, "A pool that splashes up when stepped in."),
        BattleChip(110, "CinderPit", ChipTier.STANDARD, ChipElement.FIRE, 70, listOf('X', 'E'), 24, 1, EffectKind.TRAP, "A pit of patiently waiting embers."),
        BattleChip(111, "MineField", ChipTier.MEGA, ChipElement.NULL, 60, listOf('X', 'Q'), 50, 3, EffectKind.TRAP, "Scatters three linked mines."),
        BattleChip(112, "InfernoTrap", ChipTier.MEGA, ChipElement.FIRE, 150, listOf('E', 'Q'), 58, 1, EffectKind.TRAP, "A trap with a volcano's temper."),
        BattleChip(113, "DoomBloom", ChipTier.GIGA, ChipElement.WOOD, 300, listOf('X'), 88, 1, EffectKind.TRAP, "A flower that blooms into disaster."),
        BattleChip(114, "GuardWall", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('I'), 8, 1, EffectKind.SUPPORT, "A wall that blocks the next hit."),
        BattleChip(115, "HealDew", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('I', 'O'), 10, 1, EffectKind.SUPPORT, "Morning dew that restores some HP."),
        BattleChip(116, "SpeedSeed", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('O'), 8, 1, EffectKind.SUPPORT, "A seed that makes you speedy for a while."),
        BattleChip(117, "PowerNut", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('O', 'F'), 12, 1, EffectKind.SUPPORT, "A nut that boosts your next chip's punch."),
        BattleChip(118, "PanelMend", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('F'), 10, 1, EffectKind.SUPPORT, "Repairs cracked panels on your side."),
        BattleChip(119, "BarrierBit", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('I', 'F'), 8, 1, EffectKind.SUPPORT, "A floating bit that blocks one shot."),
        BattleChip(120, "FocusLeaf", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('I'), 6, 1, EffectKind.SUPPORT, "A leaf that sharpens your aim."),
        BattleChip(121, "IronBark", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('O'), 10, 1, EffectKind.SUPPORT, "Bark armor that soaks damage briefly."),
        BattleChip(122, "SecondWind", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('F'), 12, 1, EffectKind.SUPPORT, "Catch your breath and recover a little HP."),
        BattleChip(123, "QuickStep", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('I', 'O'), 10, 1, EffectKind.SUPPORT, "Move in a blur for a short burst."),
        BattleChip(124, "GuardAura", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('O', 'F'), 12, 1, EffectKind.SUPPORT, "An aura that softens incoming hits."),
        BattleChip(125, "LuckyClover", ChipTier.STANDARD, ChipElement.PLUS, 0, listOf('I', 'O', 'F'), 14, 1, EffectKind.SUPPORT, "A clover that makes your next hits lucky."),
        BattleChip(126, "AegisDome", ChipTier.MEGA, ChipElement.PLUS, 0, listOf('I', 'O'), 35, 1, EffectKind.SUPPORT, "A dome shield that blocks everything briefly."),
        BattleChip(127, "FullBloom", ChipTier.MEGA, ChipElement.PLUS, 0, listOf('O', 'F'), 40, 1, EffectKind.SUPPORT, "A bloom that restores lots of HP."),
        BattleChip(128, "ScrapCannon", ChipTier.STANDARD, ChipElement.BREAK, 60, listOf('J'), 22, 1, EffectKind.PROJECTILE, "A heavy slug of scrap metal."),
        BattleChip(129, "PileDriver", ChipTier.STANDARD, ChipElement.BREAK, 70, listOf('J', 'Q'), 26, 1, EffectKind.PROJECTILE, "A pile-driver round. Smashes through guards."),
        BattleChip(130, "WreckBall", ChipTier.STANDARD, ChipElement.BREAK, 70, listOf('Q'), 30, 1, EffectKind.PROJECTILE, "A swinging wrecking ball, fired."),
        BattleChip(131, "IronSlug", ChipTier.STANDARD, ChipElement.BREAK, 70, listOf('Q', 'Y'), 26, 1, EffectKind.PROJECTILE, "One dense, no-nonsense iron slug."),
        BattleChip(132, "SmashTube", ChipTier.STANDARD, ChipElement.BREAK, 60, listOf('Y'), 22, 1, EffectKind.PROJECTILE, "A tube that fires pure smash."),
        BattleChip(133, "AnvilShot", ChipTier.STANDARD, ChipElement.BREAK, 70, listOf('J', 'Y'), 28, 1, EffectKind.PROJECTILE, "Fires an actual anvil. Somehow."),
        BattleChip(134, "CrushRound", ChipTier.STANDARD, ChipElement.BREAK, 70, listOf('J'), 30, 1, EffectKind.PROJECTILE, "A round that crushes whatever it hits."),
        BattleChip(135, "DoomTube", ChipTier.STANDARD, ChipElement.BREAK, 70, listOf('Q'), 28, 1, EffectKind.PROJECTILE, "The biggest tube. The biggest boom."),
        BattleChip(136, "SiegeCannon", ChipTier.MEGA, ChipElement.BREAK, 150, listOf('J', 'Q'), 55, 1, EffectKind.PROJECTILE, "A siege weapon's answer to everything."),
        BattleChip(137, "GigaSlug", ChipTier.MEGA, ChipElement.BREAK, 180, listOf('Q', 'Y'), 65, 1, EffectKind.PROJECTILE, "A slug the size of a small car."),
        BattleChip(138, "FortBuster", ChipTier.MEGA, ChipElement.BREAK, 160, listOf('J', 'Q', 'Y'), 60, 1, EffectKind.PROJECTILE, "Built to bust forts. And foes."),
        BattleChip(139, "WorldBreaker", ChipTier.GIGA, ChipElement.BREAK, 450, listOf('*'), 99, 1, EffectKind.PROJECTILE, "The cannon that breaks worlds."),
        BattleChip(140, "HomingPip", ChipTier.STANDARD, ChipElement.CURSOR, 40, listOf('C'), 14, 1, EffectKind.PROJECTILE, "A pip that curves toward the foe."),
        BattleChip(141, "ChaserOrb", ChipTier.STANDARD, ChipElement.CURSOR, 50, listOf('C', 'H'), 18, 1, EffectKind.PROJECTILE, "An orb that chases its target."),
        BattleChip(142, "WispHunter", ChipTier.STANDARD, ChipElement.CURSOR, 40, listOf('H'), 14, 1, EffectKind.PROJECTILE, "A wisp that hunts down its mark."),
        BattleChip(143, "DartSeeker", ChipTier.STANDARD, ChipElement.CURSOR, 60, listOf('H', 'R'), 22, 1, EffectKind.PROJECTILE, "A dart that never loses the scent."),
        BattleChip(144, "EchoBat", ChipTier.STANDARD, ChipElement.CURSOR, 50, listOf('R'), 18, 1, EffectKind.PROJECTILE, "A bat that echolocates its target."),
        BattleChip(145, "MagnetMote", ChipTier.STANDARD, ChipElement.CURSOR, 30, listOf('C', 'R'), 18, 2, EffectKind.PROJECTILE, "A mote drawn to foes. Twice."),
        BattleChip(146, "HoundScent", ChipTier.STANDARD, ChipElement.CURSOR, 60, listOf('C'), 22, 1, EffectKind.PROJECTILE, "A hound-nose shot that tracks."),
        BattleChip(147, "StarChaser", ChipTier.STANDARD, ChipElement.CURSOR, 70, listOf('H'), 26, 1, EffectKind.PROJECTILE, "Chases like a falling star."),
        BattleChip(148, "BloodHound", ChipTier.MEGA, ChipElement.CURSOR, 130, listOf('C', 'H'), 52, 1, EffectKind.PROJECTILE, "It has your scent. Run."),
        BattleChip(149, "SkyHunter", ChipTier.MEGA, ChipElement.CURSOR, 150, listOf('H', 'R'), 58, 1, EffectKind.PROJECTILE, "Strikes from above, unerringly."),
        BattleChip(150, "FateSeeker", ChipTier.GIGA, ChipElement.CURSOR, 320, listOf('*'), 92, 1, EffectKind.PROJECTILE, "You cannot dodge fate."),
    )

    fun byId(id: Int): BattleChip? = chips.find { it.id == id }

    fun byTier(tier: ChipTier): List<BattleChip> = chips.filter { it.tier == tier }

    fun byElement(element: ChipElement): List<BattleChip> = chips.filter { it.element == element }
}
